from person_data import DB_CONFIG, SECRET_KEY_FLASK, EMAIL, PASSWORD


class Config:
    SECRET_KEY = SECRET_KEY_FLASK
    SQLALCHEMY_DATABASE_URI = DB_CONFIG
    SQLALCHEMY_TRACK_MODIFICATIONS = True
    MAIL_SERVER = 'smtp.gmail.com'
    MAIL_PORT = 465
    MAIL_USE_SSL = True
    MAIL_USERNAME = EMAIL
    MAIL_PASSWORD = PASSWORD
    MAIL_DEFAULT_SENDER = EMAIL


